springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://pg-eadde2e-xi-cloudflare.a.aivencloud.com:13464/defaultdb?sslmode=require
    username: avnadmin
    password:
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

