spring:
  datasource:
    url: jdbc:postgresql://pg-3dfb3b5c-racke1983cn-ebca.a.aivencloud.com:24346/defaultdb?sslmode=require
    username: avnadmin
    password:
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


